version: "3.3"
services: 
  mlflow:
    build:
      context: .
      dockerfile: ./mlflow.Dockerfile
    command: [mlflow, server, --host, 0.0.0.0,--backend-store-uri, mysql+pymysql://root:password@mysql:3306/mlflow ,--default-artifact-root, s3://mlflow/]
    ports:
      - "5000:5000"
    environment: 
      MLFLOW_S3_ENDPOINT_URL: http://storage:9000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: password
      AWS_DEFAULT_REGION: us-east-1

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_DATABASE: mlflow
      MYSQL_ROOT_PASSWORD: password
    ports:
     - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql

  storage:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: password
    command: [minio, server, /data]
    ports: 
      - "9000:9000"
    volumes:
      - ./data/minio:/data